"""added task_detail.html

Revision ID: 0c28289b8aca
Revises: b602cbfeb16f
Create Date: 2023-03-27 16:46:54.003319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c28289b8aca'
down_revision = 'b602cbfeb16f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('completed',
               existing_type=sa.BOOLEAN(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_column('whendue')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whendue', sa.VARCHAR(), nullable=True))
        batch_op.alter_column('completed',
               existing_type=sa.Text(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
